In [2]:
import pandas as pd
import numpy as np

import httpimport 

from pathlib import Path

In [3]:
# Import personal library
with httpimport.github_repo('junclemente', 'jcds', ref='master'):
    import jcds.Quality as jq

In [4]:
datasets = Path('../datasets/')
df_file = 'credit_card_customers/BankChurners.csv' 
df = pd.read_csv(datasets/df_file)
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

In [5]:
df.shape

(10127, 23)

In [6]:
jq.dqr_cat(df)

The categorical features are:
['Attrition_Flag', 'Gender', 'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category']
Data Quality Report for Categorical Features
============================================
Stats
-----
           Feature  Count  Missing  % Missing  Cardinality
0   Attrition_Flag  10127        0        0.0            2
1           Gender  10127        0        0.0            2
2  Education_Level  10127        0        0.0            7
3   Marital_Status  10127        0        0.0            4
4  Income_Category  10127        0        0.0            6
5    Card_Category  10127        0        0.0            4


Mode 1
------
           Feature             Mode 1  Mode 1 Freq.  Mode 1 %
0   Attrition_Flag  Existing Customer          8500     83.93
1           Gender                  F          5358     52.91
2  Education_Level           Graduate          3128     30.89
3   Marital_Status            Married          4687     46.28
4  Income_Category     Less than $40K          3561     35.16
5    Card_Category               Blue          9436     93.18


Mode 2
------
           Feature             Mode 2  Mode 2 Freq.  Mode 2 %
0   Attrition_Flag  Attrited Customer          1627     16.07
1           Gender                  M          4769     47.09
2  Education_Level        High School          2013     19.88
3   Marital_Status             Single          3943     38.94
4  Income_Category        $40K - $60K          1790     17.68
5    Card_Category             Silver           555      5.48


Descriptive Stats
-----------------
                 count unique                top  freq
Attrition_Flag   10127      2  Existing Customer  8500
Gender           10127      2                  F  5358
Education_Level  10127      7           Graduate  3128
Marital_Status   10127      4            Married  4687
Income_Category  10127      6     Less than $40K  3561
Card_Category    10127      4               Blue  9436

In [7]:
jq.dqr_cont(df)

The non-categorical features are:
['CLIENTNUM', 'Customer_Age', 'Dependent_count', 'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon', 'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal', 'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt', 'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio', 'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1', 'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2']
Data Quality for Continous Features
Total Features: 17
                                              Feature  Count  Missing  \
0                                           CLIENTNUM  10127        0
1                                        Customer_Age  10127        0
2                                     Dependent_count  10127        0
3                                      Months_on_book  10127        0
4                            Total_Relationship_Count  10127        0
5                              Months_Inactive_12_mon  10127        0
6                               Contacts_Count_12_mon  10127        0
7                                        Credit_Limit  10127        0
8                                 Total_Revolving_Bal  10127        0
9                                     Avg_Open_To_Buy  10127        0
10                               Total_Amt_Chng_Q4_Q1  10127        0
11                                    Total_Trans_Amt  10127        0
12                                     Total_Trans_Ct  10127        0
13                                Total_Ct_Chng_Q4_Q1  10127        0
14                              Avg_Utilization_Ratio  10127        0
15  Naive_Bayes_Classifier_Attrition_Flag_Card_Cat...  10127        0
16  Naive_Bayes_Classifier_Attrition_Flag_Card_Cat...  10127        0

    % missing  Cardinality
0         0.0        10127
1         0.0           45
2         0.0            6
3         0.0           44
4         0.0            6
5         0.0            7
6         0.0            7
7         0.0         6205
8         0.0         1974
9         0.0         6813
10        0.0         1158
11        0.0         5033
12        0.0          126
13        0.0          830
14        0.0          964
15        0.0         1704
16        0.0          640


Descriptive Stats
                                                      count          mean  \
CLIENTNUM                                           10127.0  7.391776e+08
Customer_Age                                        10127.0  4.633000e+01
Dependent_count                                     10127.0  2.350000e+00
Months_on_book                                      10127.0  3.593000e+01
Total_Relationship_Count                            10127.0  3.810000e+00
Months_Inactive_12_mon                              10127.0  2.340000e+00
Contacts_Count_12_mon                               10127.0  2.460000e+00
Credit_Limit                                        10127.0  8.631950e+03
Total_Revolving_Bal                                 10127.0  1.162810e+03
Avg_Open_To_Buy                                     10127.0  7.469140e+03
Total_Amt_Chng_Q4_Q1                                10127.0  7.600000e-01
Total_Trans_Amt                                     10127.0  4.404090e+03
Total_Trans_Ct                                      10127.0  6.486000e+01
Total_Ct_Chng_Q4_Q1                                 10127.0  7.100000e-01
Avg_Utilization_Ratio                               10127.0  2.700000e-01
Naive_Bayes_Classifier_Attrition_Flag_Card_Cate...  10127.0  1.600000e-01
Naive_Bayes_Classifier_Attrition_Flag_Card_Cate...  10127.0  8.400000e-01

                                                            std          min  \
CLIENTNUM                                           36903783.45  708082083.0
Customer_Age                                               8.02         26.0
Dependent_count                                            1.30          0.0
Months_on_book                                             7.99         13.0
Total_Relationship_Count                                   1.55          1.0
Months_Inactive_12_mon                                     1.01          0.0
Contacts_Count_12_mon                                      1.11          0.0
Credit_Limit                                            9088.78       1438.3
Total_Revolving_Bal                                      814.99          0.0
Avg_Open_To_Buy                                         9090.69          3.0
Total_Amt_Chng_Q4_Q1                                       0.22          0.0
Total_Trans_Amt                                         3397.13        510.0
Total_Trans_Ct                                            23.47         10.0
Total_Ct_Chng_Q4_Q1                                        0.24          0.0
Avg_Utilization_Ratio                                      0.28          0.0
Naive_Bayes_Classifier_Attrition_Flag_Card_Cate...         0.37          0.0
Naive_Bayes_Classifier_Attrition_Flag_Card_Cate...         0.37          0.0

                                                             25%  \
CLIENTNUM                                           7.130368e+08
Customer_Age                                        4.100000e+01
Dependent_count                                     1.000000e+00
Months_on_book                                      3.100000e+01
Total_Relationship_Count                            3.000000e+00
Months_Inactive_12_mon                              2.000000e+00
Contacts_Count_12_mon                               2.000000e+00
Credit_Limit                                        2.555000e+03
Total_Revolving_Bal                                 3.590000e+02
Avg_Open_To_Buy                                     1.324500e+03
Total_Amt_Chng_Q4_Q1                                6.300000e-01
Total_Trans_Amt                                     2.155500e+03
Total_Trans_Ct                                      4.500000e+01
Total_Ct_Chng_Q4_Q1                                 5.800000e-01
Avg_Utilization_Ratio                               2.000000e-02
Naive_Bayes_Classifier_Attrition_Flag_Card_Cate...  0.000000e+00
Naive_Bayes_Classifier_Attrition_Flag_Card_Cate...  1.000000e+00

                                                             50%  \
CLIENTNUM                                           7.179264e+08
Customer_Age                                        4.600000e+01
Dependent_count                                     2.000000e+00
Months_on_book                                      3.600000e+01
Total_Relationship_Count                            4.000000e+00
Months_Inactive_12_mon                              2.000000e+00
Contacts_Count_12_mon                               2.000000e+00
Credit_Limit                                        4.549000e+03
Total_Revolving_Bal                                 1.276000e+03
Avg_Open_To_Buy                                     3.474000e+03
Total_Amt_Chng_Q4_Q1                                7.400000e-01
Total_Trans_Amt                                     3.899000e+03
Total_Trans_Ct                                      6.700000e+01
Total_Ct_Chng_Q4_Q1                                 7.000000e-01
Avg_Utilization_Ratio                               1.800000e-01
Naive_Bayes_Classifier_Attrition_Flag_Card_Cate...  0.000000e+00
Naive_Bayes_Classifier_Attrition_Flag_Card_Cate...  1.000000e+00

                                                             75%           max
CLIENTNUM                                           7.731435e+08  8.283431e+08
Customer_Age                                        5.200000e+01  7.300000e+01
Dependent_count                                     3.000000e+00  5.000000e+00
Months_on_book                                      4.000000e+01  5.600000e+01
Total_Relationship_Count                            5.000000e+00  6.000000e+00
Months_Inactive_12_mon                              3.000000e+00  6.000000e+00
Contacts_Count_12_mon                               3.000000e+00  6.000000e+00
Credit_Limit                                        1.106750e+04  3.451600e+04
Total_Revolving_Bal                                 1.784000e+03  2.517000e+03
Avg_Open_To_Buy                                     9.859000e+03  3.451600e+04
Total_Amt_Chng_Q4_Q1                                8.600000e-01  3.400000e+00
Total_Trans_Amt                                     4.741000e+03  1.848400e+04
Total_Trans_Ct                                      8.100000e+01  1.390000e+02
Total_Ct_Chng_Q4_Q1                                 8.200000e-01  3.710000e+00
Avg_Utilization_Ratio                               5.000000e-01  1.000000e+00
Naive_Bayes_Classifier_Attrition_Flag_Card_Cate...  0.000000e+00  1.000000e+00
Naive_Bayes_Classifier_Attrition_Flag_Card_Cate...  1.000000e+00  1.000000e+00